[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  nnoremap <silent> <space>u :call dein#update()<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'michaeljsmith/vim-indent-object'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_source = 'source ~/.vim/rc/plugins/airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-bundler'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source = 'source ~/.vim/rc/plugins/fugitive.rc.vim'
hook_add = '''
  nmap <leader>g :Gstatus<CR>
'''

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-rake'
hook_add = '''
  nnoremap <leader>a :AS<CR>
'''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rsi'

[[plugins]]
repo = 'tpope/vim-scriptease'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'godlygeek/tabular'
hook_add = '''
  inoremap <silent> <Bar>   <Bar><Esc>:call AutoTabularize()<CR>a
'''

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'mbbill/undotree'
hook_source = 'source ~/.vim/rc/plugins/undotree.rc.vim'
hook_add = '''
  nmap <leader>u :UndotreeToggle<CR>
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'thinca/vim-textobj-between'

[[plugins]]
repo = 'rhysd/vim-textobj-anyblock'

[[plugins]]
repo = 'sotte/presenting.vim'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
if = "has('nvim')"
hook_source = 'source ~/.vim/rc/plugins/ultisnips.rc.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  map + <Plug>(expand_region_expand)
  map - <Plug>(expand_region_shrink)
'''

